// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssignment.Api.Data;

#nullable disable

namespace TechnicalAssignment.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240128015557_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssignment.Api.Data.Entities.CarMake", b =>
                {
                    b.Property<long>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("make_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MakeId"));

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("make_name");

                    b.HasKey("MakeId");

                    b.ToTable("CarMakes");
                });
#pragma warning restore 612, 618
        }
    }
}
